version: "3.8"
services:
  backend:
    depends_on:
      - mysqldb
    build: .
    ports:
      - "8080:8080"
    environment:
        SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/usersApp?useSSL=false",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : "rand",
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rand
      - MYSQL_DATABASE=usersApp
      - MYSQL_USER=rand
      - MYSQL_PASSWORD=rand
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
